# https://kubernetes.io/docs/concepts/configuration/secret/
apiVersion: v1
kind: Secret
metadata:
  name: psql-secrets
type: Opaque
data:
  DB_USER: cG9zdGdyZXMK
  DB_PASSWORD: bXlzZWNyZXQK

  # password: {{ .Values.password | b64enc }}
---

