name: Push Docker Image (golang vote app)

on:
  push:
    branches:
      - main

jobs:
  build_image:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: test  values in main.go
        run: cat main.go

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: mikitasz/golang-vote-app:latest
